# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

f <- function(x) {
    .Call('_Statcomp20035_f', PACKAGE = 'Statcomp20035', x)
}

rwMetropolis <- function(sigma, x0, N) {
    .Call('_Statcomp20035_rwMetropolis', PACKAGE = 'Statcomp20035', sigma, x0, N)
}

